### ISSUE TITLE
npm install is erroring out.

### ISSUE THREAD

**Issue by phibersirhack** [Xotic750/truncate-x#1]
tired to save it in my package.json file, its giving following error:
 C:\Users\yadavcha\Documents\GitHub\test-app\npm-debug.log
PS C:\GitHub\test-app> npm install truncate-x --save
npm WARN deprecated safe-to-string-x@2.0.3: Moved to https://github.com/Xotic750/to-string-symbols-supported-x
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: to-integer-x@^3.0.0 (node_modules\array-like-slice-x\node_modules\to-integer-x):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected token o in JSON at position 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: [object Object]
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "truncate-x" "--save"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10

**Comment by Xotic750** [comment]
Several base packages have changed and I haven't had the time to get this far yet, unfortunately. Happy to take a PR if you can supply one.

**Comment by Xotic750** [comment]
With a newer version of npm you shouldn't have this problem because of the lock file. Anyway, I've updated the dependencies.
